### ISSUE TITLE
Use API Data

### ISSUE THREAD

**Issue by tednaphil** [corysanders3/rancidtomatillos#6]
## User Stories
- As a user, when the server returns a 500 error, I will see an error message

## Acceptance Criteria
- [x] Error message should be displayed on DOM (avoid `alert`)
- [x] Styled UI
- [x] No React warnings or errors in console
- [x] All components that receive props utilize type checking with PropTypes

**Comment by tednaphil** [comment]
I'll work on getting the type checking done!

**Comment by corysanders3** [comment]
Fetch calls setup for the movies display, and the single movie view. Also manipulated the dated before setting its state for the single movie view.

**Comment by tednaphil** [comment]
- PropTypes have been defined on Movies, Card, and SingleMovie components!
- Added release year to `selection` state to use on the SingleMovie
- Found that the details popup for movies with long titles extend beyond its parent and get hidden behind the element below it


![Image](https://github.com/corysanders3/rancidtomatillos/assets/76406423/66956f5f-4596-4973-b217-3f96c3f932fc)
